### ISSUE TITLE
Request to put the cached album art in a separate folder

### ISSUE THREAD

**Issue by farshed** [cinder92/react-native-get-music-files#51]
This is not an issue, just a feature request. The cached album art is stored in the open inside storage. It would be a better UX if it was stored inside a folder with a `.nomedia` file so it wouldn't show up in the gallery or other apps that scan media.

**Comment by Drazail** [comment]
@eff-society
You can pass a custom path to `RNAndroidAudioStore`. ( Only works on Android)

**Comment by farshed** [comment]
Thank you for responding so quick @Drazail. I just saw in the docs that RNAndroidStore.getAll() method now returns album covers but at the cost of performance.

- Is the performance same as MusicFiles.getAll() or better?

- Also, do I have to be fetching media with RNAndroidStore to make use of the coverFolder property or does this work with MusicFiles as well?

**Comment by Drazail** [comment]
@eff-society 

* performance should be marginally better than `MusicFiles.getAll` (opening streams and writing into files will introduce some performance hit, even though they are being done on a separate thread).

* yes, you will have to use `RNAndroidAudioStore`, the two are completely separate entities (due to legacy support).


as a side note, the version we are using internally does include sorting and pagination. its testing is almost done, and I will hopefully push these new features into this repo soon ( `.nomedia` idea is an interesting one as well, will try to add it as an option in the same release). meanwhile you can use `delay` and `batchNumber` parameters on `RNAndroidAudioStore.getAll` ( and listening to events using `DeviceEventEmitter` )to minimize the performance hit.

**Comment by DNA-h** [comment]
The problem is android side is that all the images are added to the user's gallery, so cover folder and .nomedia file make sense.
