### ISSUE TITLE
getAll() returns data that no longer exists

### ISSUE THREAD

**Issue by farshed** [cinder92/react-native-get-music-files#53]
I'm using [react-native-fs](https://github.com/itinance/react-native-fs)'s moveFile method to rename files in my app. The package works correctly (confirmed with file explorer and other music players).

But when I scan after the rename operation,

- RNAndroidAudioStore.getAll() returns a strange object for the renamed file.
Note that the path property is the old url which no longer exists. Also there's no cover property.

![Screenshot (144)](https://user-images.githubusercontent.com/23633421/59928159-8f5fda00-9457-11e9-935b-501b6d386b03.png)

- MusicFiles.getAll() on the other hand, entirely ignores the renamed file and doesn't include it in the returned data

**Comment by Drazail** [comment]
@eff-society 
ill take a look into this, meanwhile please reset the emulator, scan the files again and let us know the results.

also are you using events ( via `batchNumber` option) or are these being returned directly by the `getAll` method?

it would be great if you could reproduce the issue as well.

**Comment by farshed** [comment]
@Drazail 
The problem persists even after:

- Restarting the app.
- Clearing app data.
- Reinstalling the app.

But goes away (`getAll()` returns the correct object):

- After rebooting the emulator.

I've tried both events and getAll() without batchNumber btw.

**Comment by Drazail** [comment]
@eff-society 
the problem seems to be originating from `moveFile` not triggering android media scanner.
when a file is moved, the corresponding entry in `MediaStore.Audio` (android's database) stays the same unless the scanner is triggered manually ( or via the automatic scan which happens when the device is booting up). so when the package tries to scan the path provided by `MediaStore.Audio` it fails hence no cover property.

I noticed that `react-native-fs` community proposed a solution by introducing a scan method:
itinance/react-native-fs#79
`scanFile(path: string): Promise<string[]>`

**Comment by farshed** [comment]
Thank you @Drazail. That was very helpful😄
