### ISSUE TITLE
Sorting Features and Duration 

### ISSUE THREAD

**Issue by ajoykarmakar459** [cinder92/react-native-get-music-files#66]
How can we sort the array list that returns by the plugin, Like sort by date or size and can we get the duration in minutes or hours more user-readable instead of milliseconds?

**Comment by Drazail** [comment]
@ajoykarmakar459 

about sorting, we have implemented sorting and pagination internally, however the testing is not complete, and as we are very close to pushing a major update, i'm unfortunately extremely busy.

I try my best to make a pull request as soon as the code is tested for the wider use cases this package requires (compared to our app).

as for "user-readable" duration, i think it would be better if you handle that using third-party libraries such as [numeraljs](https://github.com/adamwdraper/Numeral-js) .

**Comment by cinder92** [comment]
@Drazail please share with me, those mayor changes, im going to work on some issues today

**Comment by Drazail** [comment]
@cinder92 
sorry for the late response, due to some "difficulties" the internet of my home country ( yes, the whole country  :-| ) was down for a week ... 

the proper way of pushing new features to this repo, I think, is to create a new branch ( V3 or AndroidX or something like that) so we can add RN 0.6 + support without loosing backwards compatibility.

If you think its a good idea, we can open another issue to discuss new features and AndroidX support further.

**Comment by cinder92** [comment]
@Drazail yep, sounds good, we need to migrate to android X and RN 0.60+, lets open an issue for it

**Comment by cinder92** [comment]
@ajoykarmakar459 please test version 2.2.2 i added feature to sort. Thanks.
